### ISSUE TITLE
Support for HLS m3u8 streams

### ISSUE THREAD

**Issue by DoNotSpamPls** [Walkyst/lavaplayer-fork#14] opened 2021-11-28 19:14 UTC
Support for HLS m3u8 streams

Self explanatory - HLS m3u8 streams don't contain a direct link, but instead update with temporary files every 10 seconds or so. It'd be nice if those could be played using lavaplayer.

Link you can use for testing: https://bss.neterra.tv/rtplive/veselinaradio_live.stream/chunklist.m3u8

(related: sedmelluq/lavaplayer#174)

**Comment by spectral369** [comment] 2022-01-10 10:09
This indeed is an issue ! +1
.m3u8 / .m3u

**Comment by bananasmoothii** [comment] 2022-01-16 09:38
+1 I'm constantly having that issue because a lot of webradios are m3u8 streams

**Comment by DoNotSpamPls** [comment] 2022-03-06 21:29
@Walkyst any comment on this?

**Comment by Walkyst** [comment] 2022-03-06 21:38
At least not will be in 1.3.98, maybe in future i will look into this, feel free to do a PR with support for m3u8 streams

**Comment by spectral369** [comment] 2022-03-12 12:59
I'll leave a link for future improvement:
http://live4ro.antenaplay.ro//radiozu/radiozu-48000.m3u8
Also  in package : com.sedmelluq.discord.lavaplayer.container.playlists  -> class:  M3uPlaylistContainerProbe -> HlsStreamSegmentUrlProvider.findHlsEntryUrl(lines); returns null 
that comes from class M3uStreamSegmentUrlProvider directive name check EXT-X-STREAM-INF that is not present !
But 1st checking should be done in ExtendedM3uParser because it doesn't seem to parse correctly *new* HLS streams.
Sorry that I lack the knowledge of hls to fix this, hope this will help in the future  :-)
*sighs*

**Comment by pablo67340** [comment] 2023-10-19 01:54
+1 to this. I have reviewed a ton of the code, I've been working on several fixes for this thanks to the message from @spectral369. I have been attempting to add SiriusXM to my bot for some time, which requires m3u8. I have all the Sirius stuff working, m3u8 no luck. Fingers crossed, hoping to throw a working PR up soon.

**Comment by devoxin** [comment] 2023-12-01 02:37
I've made a potential fix for this over at my fork if anyone would like to test it - https://github.com/Devoxin/lavaplayer/commit/48d1a10d977d2e382c92fa09e8e3ffbfdd8b8528

Hopefully walkyst will port this back to this fork, if not I may look at making a PR within the next week or so.

Edit: It seems I didn't completely read the thread. This commit adds support for HLS playlists containing relative URLs to resources rather than absolute.

**Comment by pablo67340** [comment] 2023-12-01 19:55
@devoxin Have you tested this yet? Or shall I using a verified M3u8 source?

**Comment by devoxin** [comment] 2023-12-02 02:09
> @devoxin Have you tested this yet? Or shall I using a verified M3u8 source?

@pablo67340 I've tested it and it appears to work fine.
Additionally, I think I have implemented a solution to the original issue here -- Lavaplayer doesn't distinguish between inner and outer m3u playlists causing it to treat inner playlists as outer thus trying to load the contents as URLs. I have released a patch for this in my fork.

https://github.com/devoxin/lavaplayer/pull/5

I should add, though...

> [!WARNING]
In my testing, some m3u playlists still won't play. I believe this to be caused by lack of proper codec support (particularly streams encoded with HE-AACv2) but that's more than just a codebase change -- that requires an update of natives as well afaik.

**Comment by pablo67340** [comment] 2023-12-02 06:02
@devoxin Would you be willing to collab on Discord with this?

I am attempting to play a proxied m3u8 from SiriusXM. Sirius requires API stuff to be sent in the headers, and all that is handled through a proxy. It sends my API credentials, gets the m3u8 link, then proxies it so the Discord bot can access the .m3u8 without needing authentication stuff. However when I try to play an m3u8 with your link, it doesnt play, and prints:

`[main] WARN net.dv8tion.jda.api.JDA - Automatically disabled CacheFlags due to missing intents
[main] WARN net.dv8tion.jda.api.JDA - Disabled CacheFlag.SCHEDULED_EVENTS (missing GatewayIntent.SCHEDULED_EVENTS)
[main] WARN net.dv8tion.jda.api.JDA - You can manually disable these flags to remove this warning by using disableCache(CacheFlag.SCHEDULED_EVENTS) on your JDABuilder
[main] INFO net.dv8tion.jda.api.JDA - Login Successful!
[JDA MainWS-WriteThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!
Args1: http://127.0.0.1:8888/9413.m3u8
Args2: http://127.0.0.1:8888/9413.m3u8
[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$317/0x00000008012de5e8@4c646092
New Instance!
Now Playing Running!
[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library libmpg123-0: successfully loaded.
[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library connector: loading with filter null
[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library connector: successfully loaded.`

But nothing else happens. If I load the same link in VLC player, it plays fine?

Discord: @Vajoner

**Closed as completed** 2024-01-23 22:31 UTC
