### ISSUE TITLE
Feature request: Switch HTTP client library from `Apache HttpClient 4.x` to `Apache HttpClient 5.x` (or `okhttp` / etc...)

### ISSUE THREAD

**Issue by JellyBrick** [Walkyst/lavaplayer-fork#44] opened 2022-04-25 14:15 UTC
`Apache HttpClient 5.x` and `okhttp` (or `ktor`) support `HTTP/2` (and asynchronous HTTP requests).

Switching to these libraries is expected to enable more efficient HTTP requests.

Migrate issue from https://github.com/sedmelluq/lavaplayer/issues/652

**Comment by Walkyst** [comment] 2022-04-25 14:46
Feel free to do PR

**Comment by jocull** [comment] 2023-03-25 21:32
Is there a major benefit to doing this? Is the current version causing any problems?

**Comment by JellyBrick** [comment] 2023-04-08 02:01
@jocull 
> Is there a major benefit to doing this? Is the current version causing any problems?

`HttpClient` has the problem of being overly complex and requires writing tons of class implementation. This issue makes it difficult to resolve issues like #86.

In addition, `HttpClient 4` does not support HTTP 2.0. This is not appropriate for lavaplayer where video streams need to be downloaded continuously.

**Comment by EncryptSL** [comment] 2023-04-25 00:46
This need very great knowledge of changes between 4x and 5x.

**Comment by jocull** [comment] 2023-04-25 02:33
I did take a look at this there are two things worth noting:

1. Many of the public interfaces accept specific configurations or builders and then seems to use them throughout the library. Because of the public facing nature of the client, this upgrade is a breaking change that will require other uses to update their code to use and configure for the new HTTP library as well.
2. The scope of work is relatively large, requiring something like 50 classes to be changed.

I haven't been able to scope or examine the changes further. I think at this point the value should be questioned again since it's a major change for not just the library itself, but everyone that depends on it 🙂

**Comment by JellyBrick** [comment] 2023-04-25 03:19
Agree, I think it can cause a lot of breaking changes.

Pros:

- lavaplayer's complex HttpClient setup has caused memory leaks and other bugs in the past, I think moving to a simpler HTTP client library will help with maintenance.
(https://github.com/sedmelluq/lavaplayer/commit/0480e1ad6c721c4cb3f0505dfd379570aeeba299)
(https://github.com/sedmelluq/lavaplayer/issues/514)
(#86)

- Can easily configure new features such as Brotli, cache, etc.

Cons: 

- It requires a large amount of change (over 50 classes)
- **Can break third-party libraries that rely on lavaplayer caused by breaking changes**

**Comment by jocull** [comment] 2023-04-25 04:24
I skimmed some of the issues. I can't tell how much of the issue is from user provided misconfiguration vs the library is not cleaning up after itself.

I think I would personally make the goal to make the library harder to misconfigure (and fix any obvious bugs within it like not closing connections that should be closed). Those can be treated separately.

Perhaps instead of exposing implementation to _specific_ HttpBuilders for example, expose a number of tunable properties. The max number of connections, the max time to hold a connection open, etc. Maybe there's ways to improve specific issues people are having before a wholesale library change?

**Closed as completed** 2024-01-23 22:32 UTC
