### ISSUE TITLE
Something broke when playing the track.

### ISSUE THREAD

**Issue by SquareCodeFX** [Walkyst/lavaplayer-fork#121] opened 2023-07-31 15:42 UTC
FriendlyException: Something broke when playing the track.
com.sedmelluq.discord.lavaplayer.tools.ExceptionTools in wrapUnfriendlyExceptions at line 44
com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor in execute at line 116
com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager in lambda$executeTrack$1 at line 361
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1144
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 642
java.lang.Thread in run at line 1589

RuntimeException Not success status code: 403
com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream in validateStatusCode at line 87
com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream in attemptConnect at line 123
com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream in connect at line 105
com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream in internalRead at line 157
com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream in read at line 173
java.io.DataInputStream in readByte at line 271
com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader in readEbmlInteger at line 39
com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader in readNextElement at line 45
com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile in readFile at line 78
com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack in loadMatroskaFile at line 51
com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack in process at line 34
com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack in processDelegate at line 25
com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack in processStatic at line 58
com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack in process at line 50
com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor in execute at line 104
com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager in lambda$executeTrack$1 at line 361
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1144
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 642
java.lang.Thread in run at line 1589

**Comment by topi314** [comment] 2023-07-31 16:00
Duplicate of https://github.com/Walkyst/lavaplayer-fork/issues/108

**Closed as completed** 2024-01-23 22:35 UTC
